// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: users_chats.sql

package database

import (
	"context"
)

const createUserChat = `-- name: CreateUserChat :one
INSERT INTO
  users_chats (user_id, chat_id)
VALUES
  ($1, $2)
RETURNING
  user_id,
  chat_id
`

type CreateUserChatParams struct {
	UserID int32
	ChatID int32
}

func (q *Queries) CreateUserChat(ctx context.Context, arg CreateUserChatParams) (UsersChat, error) {
	row := q.db.QueryRow(ctx, createUserChat, arg.UserID, arg.ChatID)
	var i UsersChat
	err := row.Scan(&i.UserID, &i.ChatID)
	return i, err
}

const getUsersChat = `-- name: GetUsersChat :one
SELECT
  user_id,
  chat_id
FROM
  users_chats
WHERE
  user_id = $1
  AND chat_id = $2
`

type GetUsersChatParams struct {
	UserID int32
	ChatID int32
}

func (q *Queries) GetUsersChat(ctx context.Context, arg GetUsersChatParams) (UsersChat, error) {
	row := q.db.QueryRow(ctx, getUsersChat, arg.UserID, arg.ChatID)
	var i UsersChat
	err := row.Scan(&i.UserID, &i.ChatID)
	return i, err
}
